### ISSUE TITLE
be_manager_relation 

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/yform_ui#1]
be_manager_relation "Breite" wird nicht in die DB geschrieben 

yform: 4.0.0
yform_ui: aktuelle GitHub Version

![image](https://user-images.githubusercontent.com/330516/149094034-24392d22-a9b6-41b1-b7d4-58b101530e40.png)
![image](https://user-images.githubusercontent.com/330516/149094255-86bb0b49-c1aa-4217-b369-cbce3b390eff.png)

**Comment by olien** [comment]
Wenn ich den wert (33,333...) "von Hand" in das DB Feld eintrage wird das bei der Ausgabe nicht berücksichtigt...

**Comment by eaCe** [comment]
@olien ich konnte es bisher leider nicht reproduzieren. 
Ich lass das mal offen, vielleicht passiert das andren auch.

**Comment by eaCe** [comment]
@olien ich werde, auch auf anraten von @skerbis von % auf Klassen umstellen. So wird es default Bootstrap 3 sein und sonst kann man anpassen was man so braucht.

**Comment by olien** [comment]
Gleiches Problem habe ich bei Choice Feldern. 
Wert in DB: 50%

![image](https://user-images.githubusercontent.com/330516/150112593-4c64313f-b6bb-49c8-81f4-e95a69f46f0b.png)

**Comment by eaCe** [comment]
Ich bin nicht  sicher ob das auch mit yForm 4 zusammenhängt. Werde es am Wochenende testen.

**Comment by olien** [comment]
Auf der Testseite funktioniert es einwandfrei
