### ISSUE TITLE
Funktion Massenbearbeitung mit aktiviertem yform_ui wirft Fehler und ist nicht möglich

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/yform_ui#10]
Transaktion wurde wegen folgendem Fehler nicht ausgeführt: YUi::isIgnored(): Argument #1 ($formName) must be of type string, null given

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.1
PHP: 8.1
Database:
Browser: 
AddOns: Yform 4.0.4

**Did it whoops? / Whoops erhalten?**

**Comment by eaCe** [comment]
Danke für den Hinweis, schaue ich mir die Woche an.

**Comment by eaCe** [comment]
Ich kann es bisher nicht reproduzieren, und meine Daten werden auch nicht veändert? :|

**Comment by eaCe** [comment]
`public static function isIgnored(string|null $formName): bool {` würde funktionieren, dann müsste ich auf PHP 8 setzen. 
Wobei < 8 ja sowieso deprecated ist. Mache ich später
