### ISSUE TITLE
CSRF-Token-Error

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/yform_ui#4]
Moin! Ich hatte den Thread im Slack verfolgt und dein kleines Tool heute auch mal ausprobiert.
Danke erstmal dafür, dass ist eine sehr sinnvolle Extension für yForm :)

Ich kriege es allerdings nicht zum Laufen:
`Bitte das Formular erneut absenden, bzw. die Aktion erneut ausführen (Fehler: CSRF-Token ungültig).`

Das bekomme ich IMMER wenn ich im Table-Manager ein Feld editieren möchte. Ich hab Cache gelöscht, hab mich neu eingeloggt, aber es ist immer das gleiche. :(

Redaxo ist aktuell mit 5.13.2 und Server läuft auf PHP 8.0.13... any ideas?

**Comment by eaCe** [comment]
Danke schon mal für's testen, wenn auch ohne Erfolg :/
Ich hatte bisher keinerlei Probleme in dieser Art. Allerdings habe ich das ganze auch noch nicht mit PHP > 8 getestet. 
Mit yForm 4 läuft es bei mir in der Testumgebung. 
Kannst du mir vielleicht sagen welche Felder du nutzt? 
Oder vielleicht mal eine Testtabelle mit nur einem Textfeld probieren?
Aktuell habe ich leider noch keine Idee wo das Problem entstehen könnte.

**Comment by dpf-dd** [comment]
![yformui](https://user-images.githubusercontent.com/10958385/149833607-ed32aff7-db35-4c0c-93f6-9e1f39c184c0.png)

Also hab jetzt mal ne neue Tabelle angelegt und wollte ein Feld erstellen... Siehe Screenshot...
Interessant: Das Select-Auswahlfeld für die col-size wird im ADD/EDIT-Modus des Formulars angezeigt, aber wenn es die Fehlermeldung schmeißt, dann fehlt das Feld unten über dem Button. Ich vermute, da zündet der Einklink-EP nicht, aber das ist ggf. ein anderes "Problem"...

**Comment by eaCe** [comment]
Ich konnte es reproduzieren. 
Es scheint als würde der Wert von ‚_csrf_token‘ mit der Breite überschrieben.
Das kann man z.B. hier beobachten: https://github.com/yakamara/redaxo_yform/blob/d252e5cb0f031e5731c063fa818eccca03473b18/lib/yform.php#L354

Wenn man dort folgendes dumpt kann man das sehen:
dump($ValueObject->getName());
dump($ValueObject->getValue());

Warum das so ist weiß ich noch nicht. Das ist mit bei yForm 3 nicht aufgefallen, auch nicht wenn nach 3 die 4er installiert wurde.

**Comment by olien** [comment]
Hab gerade den selben Fehler. nur zur Info.
YForm 4.0.0
PHP 7.4.27

**Comment by eaCe** [comment]
@olien @dpf-dd ich habe den Fehler gefunden. Gerne noch mal mit der aktuellen Version testen.
Möglicherweise auch ein fix für das andere Problem (#1)? Da ich es bisher nicht reproduziern konnte, kann ich das leider nicht einschätzen.

**Comment by olien** [comment]
Ein träümchen. es funktioniert. danke sehr!

**Comment by dpf-dd** [comment]
Jo, super! Bei mir geht es jetzt auch. Danke für den schnellen Fix! :)

**Comment by dpf-dd** [comment]
Warum kriegt der Oli ein Herzchen und ich nur nen Daumen? *schnief* ;)
