### ISSUE TITLE
be_manager_relation Problem

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/yform_ui#5]
Mit be_manager_relation weiterer Tabellen zieht sich ein Fehler durch...

![image](https://user-images.githubusercontent.com/330516/150486479-303f6bb8-a627-4253-a530-bc965fabf548.png)

**Comment by ascky-thorben** [comment]
@olien wenn du irgendwann Zeit findest kannst du das dann noch mal prüfen? 
Ich weiß nicht ob #1 dadurch auch behoben wurde.

**Comment by eaCe** [comment]
@olien wenn du irgendwann Zeit findest kannst du das dann noch mal prüfen?
Ich weiß nicht ob #1 dadurch auch behoben wurde.

**Comment by olien** [comment]
Auf der Testseite funktioniert es einwandfrei
